/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import software.amazon.awssdk.transfer.s3.model.CompletedFileUpload;

import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;

public class App {

    HashSet<String> ignored = new HashSet<String>();

    App(){
        ignored.add("history.db");
        ignored.add(".DS_Store");
    }

    public ArrayList<FileDetails> getFiles(String dir, String base_path){

        ArrayList<FileDetails> files = new ArrayList<>();

        File folder = new File(dir);

        File[] listFiles = folder.listFiles();

        if (listFiles == null) return files;

        for (File file: listFiles) {

            if (file.isFile() && !ignored.contains(file.getName())){

                FileDetails f = new FileDetails(file.getAbsolutePath(), base_path);
                files.add(f);
            } else {
                files.addAll(getFiles(file.getAbsolutePath(), base_path));
            }
        }
        return files;
    }

    public static void main(String[] args) {

        String path = args[args.length - 1];
        App app = new App();
        ArrayList<FileDetails> files = app.getFiles(path, path);
        files.forEach(System.out::println);
        Database db = new Database(path);
        db.connect();
        db.createTable(path);

        app.uploadFiles(files, db);
    }

    public void uploadFiles(ArrayList<FileDetails> files, Database db){
        System.out.println(files.size());
        AwsClient client = new AwsClient();

        System.out.println("Starting Upload");

        for(FileDetails file: files){
            db.insertFile(file);
            if (db.checkUpload(file)) {
                CompletedFileUpload res = client.uploadFile(file);
                db.uploadFile(file);
                System.out.println("Uploaded: " + file);
            }
        }
        System.out.println("Upload Complete");
    }
}
